In [46]:
import pandas as pd
import matplotlib.pyplot as plt
import json
import scipy.stats as st
import numpy as np
import requests
from config import g_key

In [47]:
file_path = "Resources\\MoviesOnStreamingPlatforms_updated.csv"

df = pd.read_csv(file_path)

df.head()

,Unnamed: 0,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime
0,0,1,Inception,2010,13+,8.8,87%,1,0,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,1,2,The Matrix,1999,18+,8.7,87%,1,0,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,2,3,Avengers: Infinity War,2018,13+,8.5,84%,1,0,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,3,4,Back to the Future,1985,7+,8.5,96%,1,0,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,97%,1,0,1,0,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0

In [48]:
df.drop(columns=["Rotten Tomatoes","Directors","Type","Unnamed: 0"], inplace=True)

df.head()

,ID,Title,Year,Age,IMDb,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime
0,1,Inception,2010,13+,8.8,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,2,The Matrix,1999,18+,8.7,1,0,0,0,"Action,Sci-Fi",United States,English,136.0
2,3,Avengers: Infinity War,2018,13+,8.5,1,0,0,0,"Action,Adventure,Sci-Fi",United States,English,149.0
3,4,Back to the Future,1985,7+,8.5,1,0,0,0,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,1,0,1,0,Western,"Italy,Spain,West Germany",Italian,161.0

In [49]:
complete_df = df.loc[~((df['IMDb'].isnull() )|(df['Genres'].isnull())|(df['Language'].isnull())|(df["Country"].isnull())|(df['Age'].isnull()))]

complete_df.shape

(7192, 13)

In [50]:
complete_df

,ID,Title,Year,Age,IMDb,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime
0,1,Inception,2010,13+,8.8,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,2,The Matrix,1999,18+,8.7,1,0,0,0,"Action,Sci-Fi",United States,English,136.0
2,3,Avengers: Infinity War,2018,13+,8.5,1,0,0,0,"Action,Adventure,Sci-Fi",United States,English,149.0
3,4,Back to the Future,1985,7+,8.5,1,0,0,0,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,1,0,1,0,Western,"Italy,Spain,West Germany",Italian,161.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16726,16727,Richie Rich's Christmas Wish,1998,all,4.1,0,0,0,1,"Comedy,Family",United States,English,84.0
16727,16728,The Jungle Book: Mowgli's Story,1998,all,4.2,0,0,0,1,"Adventure,Family",United States,English,77.0
16737,16738,The Bears and I,1974,all,6.2,0,0,0,1,"Drama,Family",United States,English,89.0
16738,16739,Whispers: An Elephant's Tale,2000,all,5.0,0,0,0,1,"Adventure,Family",United States,English,72.0
16740,16741,The Poof Point,2001,7+,4.7,0,0,0,1,"Comedy,Family,Sci-Fi",United States,English,90.0

## Country split for partial DataFrame with country_df -TEST-

In [56]:
# new data frame with selected columns to be analysed  
country_df = complete_df[["IMDb","Title","Year","Genres","Country"]]
country_df

,IMDb,Title,Year,Genres,Country
0,8.8,Inception,2010,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom"
1,8.7,The Matrix,1999,"Action,Sci-Fi",United States
2,8.5,Avengers: Infinity War,2018,"Action,Adventure,Sci-Fi",United States
3,8.5,Back to the Future,1985,"Adventure,Comedy,Sci-Fi",United States
4,8.8,"The Good, the Bad and the Ugly",1966,Western,"Italy,Spain,West Germany"
...,...,...,...,...,...
16726,4.1,Richie Rich's Christmas Wish,1998,"Comedy,Family",United States
16727,4.2,The Jungle Book: Mowgli's Story,1998,"Adventure,Family",United States
16737,6.2,The Bears and I,1974,"Drama,Family",United States
16738,5.0,Whispers: An Elephant's Tale,2000,"Adventure,Family",United States
16740,4.7,The Poof Point,2001,"Comedy,Family,Sci-Fi",United States

In [90]:
#Separate data from Country column
xplodecountry_df= country_df.assign(Country=df.Country.str.split(",")).explode('Country')
xplodecountry_df

,IMDb,Title,Year,Genres,Country
0,8.8,Inception,2010,"Action,Adventure,Sci-Fi,Thriller",United States
0,8.8,Inception,2010,"Action,Adventure,Sci-Fi,Thriller",United Kingdom
1,8.7,The Matrix,1999,"Action,Sci-Fi",United States
2,8.5,Avengers: Infinity War,2018,"Action,Adventure,Sci-Fi",United States
3,8.5,Back to the Future,1985,"Adventure,Comedy,Sci-Fi",United States
...,...,...,...,...,...
16726,4.1,Richie Rich's Christmas Wish,1998,"Comedy,Family",United States
16727,4.2,The Jungle Book: Mowgli's Story,1998,"Adventure,Family",United States
16737,6.2,The Bears and I,1974,"Drama,Family",United States
16738,5.0,Whispers: An Elephant's Tale,2000,"Adventure,Family",United States
16740,4.7,The Poof Point,2001,"Comedy,Family,Sci-Fi",United States

In [91]:
#Sorting data by descending order in IMDb rating column
sortxplodecountry_df= xplodecountry_df.sort_values('IMDb',ascending=False)
sortxplodecountry_df

,IMDb,Title,Year,Genres,Country
7491,9.1,Finding Family,2013,"Documentary,Family,History,War",Bosnia and Herzegovina
7491,9.1,Finding Family,2013,"Documentary,Family,History,War",United Kingdom
3560,9.0,The Dark Knight,2008,"Action,Crime,Drama,Thriller",United Kingdom
3560,9.0,The Dark Knight,2008,"Action,Crime,Drama,Thriller",United States
6840,8.9,Peter Gabriel: Secret World Live,1993,"Documentary,Music",Canada
...,...,...,...,...,...
13470,1.6,Izzie's Way Home,2016,"Animation,Adventure",Hong Kong
15735,1.6,The Legend of the Titanic,1999,"Animation,Family,Fantasy,Romance",Spain
13470,1.6,Izzie's Way Home,2016,"Animation,Adventure",United Kingdom
15556,1.5,Diamond Dawgs,2009,"Action,Crime,Drama",United States
13681,1.0,Justin Bieber: Rise to Fame,2011,Documentary,United Kingdom

In [92]:
#Sorting data by descendign order in IMDb rating column and ascending Country to guarantee different results than USA
sortxplodecountry2_df = xplodecountry_df.sort_values(by =['IMDb','Country'], ascending=[False,True])
sortxplodecountry2_df

,IMDb,Title,Year,Genres,Country
7491,9.1,Finding Family,2013,"Documentary,Family,History,War",Bosnia and Herzegovina
7491,9.1,Finding Family,2013,"Documentary,Family,History,War",United Kingdom
3560,9.0,The Dark Knight,2008,"Action,Crime,Drama,Thriller",United Kingdom
3560,9.0,The Dark Knight,2008,"Action,Crime,Drama,Thriller",United States
6840,8.9,Peter Gabriel: Secret World Live,1993,"Documentary,Music",Canada
...,...,...,...,...,...
15735,1.6,The Legend of the Titanic,1999,"Animation,Family,Fantasy,Romance",United States
15837,1.6,Life's a Jungle: Africa's Most Wanted,2012,"Animation,Family",United States
16631,1.6,Jonas Brothers: The Concert Experience,2009,"Documentary,Music",United States
15556,1.5,Diamond Dawgs,2009,"Action,Crime,Drama",United States
13681,1.0,Justin Bieber: Rise to Fame,2011,Documentary,United Kingdom

In [76]:
#Get Unique Values of a Column with drop_duplicates() for a specific column Title
sortxplodecountry2_df.drop_duplicates(subset=['Title'])

,IMDb,Title,Year,Genres,Country
7491,9.1,Finding Family,2013,"Documentary,Family,History,War",Bosnia and Herzegovina
3560,9.0,The Dark Knight,2008,"Action,Crime,Drama,Thriller",United Kingdom
6840,8.9,Peter Gabriel: Secret World Live,1993,"Documentary,Music",Canada
4829,8.9,The Mountain II,2016,"Action,Drama,War",Turkey
7643,8.8,Machine Gun Preacher Documentary,2014,Documentary,Australia
...,...,...,...,...,...
15735,1.6,The Legend of the Titanic,1999,"Animation,Family,Fantasy,Romance",Italy
15837,1.6,Life's a Jungle: Africa's Most Wanted,2012,"Animation,Family",United States
16631,1.6,Jonas Brothers: The Concert Experience,2009,"Documentary,Music",United States
15556,1.5,Diamond Dawgs,2009,"Action,Crime,Drama",United States
13681,1.0,Justin Bieber: Rise to Fame,2011,Documentary,United Kingdom

## Country split for full DataFrame with complete_df

In [177]:
#Do the same but for the full Data Frame
print("----------------------------")
print(f"Complete Country text split DataFrame")
print("----------------------------")
complete_df

----------------------------
Complete Country text split DataFrame
----------------------------

,ID,Title,Year,Age,IMDb,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime,Total Services
0,1,Inception,2010,13+,8.8,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0,1
1,2,The Matrix,1999,18+,8.7,1,0,0,0,"Action,Sci-Fi",United States,English,136.0,1
2,3,Avengers: Infinity War,2018,13+,8.5,1,0,0,0,"Action,Adventure,Sci-Fi",United States,English,149.0,1
3,4,Back to the Future,1985,7+,8.5,1,0,0,0,"Adventure,Comedy,Sci-Fi",United States,English,116.0,1
4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,1,0,1,0,Western,"Italy,Spain,West Germany",Italian,161.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16726,16727,Richie Rich's Christmas Wish,1998,all,4.1,0,0,0,1,"Comedy,Family",United States,English,84.0,1
16727,16728,The Jungle Book: Mowgli's Story,1998,all,4.2,0,0,0,1,"Adventure,Family",United States,English,77.0,1
16737,16738,The Bears and I,1974,all,6.2,0,0,0,1,"Drama,Family",United States,English,89.0,1
16738,16739,Whispers: An Elephant's Tale,2000,all,5.0,0,0,0,1,"Adventure,Family",United States,English,72.0,1
16740,16741,The Poof Point,2001,7+,4.7,0,0,0,1,"Comedy,Family,Sci-Fi",United States,English,90.0,1

In [114]:
#Separate data from Country column
xplodecountry_df= complete_df.assign(Country=df.Country.str.split(",")).explode('Country')
xplodecountry_df

,ID,Title,Year,Age,IMDb,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime
0,1,Inception,2010,13+,8.8,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller",United States,"English,Japanese,French",148.0
0,1,Inception,2010,13+,8.8,1,0,0,0,"Action,Adventure,Sci-Fi,Thriller",United Kingdom,"English,Japanese,French",148.0
1,2,The Matrix,1999,18+,8.7,1,0,0,0,"Action,Sci-Fi",United States,English,136.0
2,3,Avengers: Infinity War,2018,13+,8.5,1,0,0,0,"Action,Adventure,Sci-Fi",United States,English,149.0
3,4,Back to the Future,1985,7+,8.5,1,0,0,0,"Adventure,Comedy,Sci-Fi",United States,English,116.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16726,16727,Richie Rich's Christmas Wish,1998,all,4.1,0,0,0,1,"Comedy,Family",United States,English,84.0
16727,16728,The Jungle Book: Mowgli's Story,1998,all,4.2,0,0,0,1,"Adventure,Family",United States,English,77.0
16737,16738,The Bears and I,1974,all,6.2,0,0,0,1,"Drama,Family",United States,English,89.0
16738,16739,Whispers: An Elephant's Tale,2000,all,5.0,0,0,0,1,"Adventure,Family",United States,English,72.0
16740,16741,The Poof Point,2001,7+,4.7,0,0,0,1,"Comedy,Family,Sci-Fi",United States,English,90.0

In [115]:
#Sorting data by descendign order in IMDb rating column and ascending Country to guarantee different results than USA
sortcountry_df = xplodecountry_df.sort_values(by =['IMDb','Country'], ascending=[False,True])
sortcountry_df

,ID,Title,Year,Age,IMDb,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime
7491,7492,Finding Family,2013,13+,9.1,0,0,1,0,"Documentary,Family,History,War",Bosnia and Herzegovina,"Bosnian,English",56.0
7491,7492,Finding Family,2013,13+,9.1,0,0,1,0,"Documentary,Family,History,War",United Kingdom,"Bosnian,English",56.0
3560,3561,The Dark Knight,2008,13+,9.0,0,1,0,0,"Action,Crime,Drama,Thriller",United Kingdom,"English,Mandarin",152.0
3560,3561,The Dark Knight,2008,13+,9.0,0,1,0,0,"Action,Crime,Drama,Thriller",United States,"English,Mandarin",152.0
6840,6841,Peter Gabriel: Secret World Live,1993,all,8.9,0,0,1,0,"Documentary,Music",Canada,English,102.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15735,15736,The Legend of the Titanic,1999,all,1.6,0,0,1,0,"Animation,Family,Fantasy,Romance",United States,Italian,84.0
15837,15838,Life's a Jungle: Africa's Most Wanted,2012,all,1.6,0,0,1,0,"Animation,Family",United States,English,101.0
16631,16632,Jonas Brothers: The Concert Experience,2009,all,1.6,0,0,0,1,"Documentary,Music",United States,English,76.0
15556,15557,Diamond Dawgs,2009,18+,1.5,0,0,1,0,"Action,Crime,Drama",United States,English,90.0
13681,13682,Justin Bieber: Rise to Fame,2011,all,1.0,0,0,1,0,Documentary,United Kingdom,English,65.0

In [117]:
#Get Unique Values of a Column with drop_duplicates() for a specific column Title
dropcountry_df= sortcountry_df.drop_duplicates(subset=['Title'])
dropcountry_df

,ID,Title,Year,Age,IMDb,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime
7491,7492,Finding Family,2013,13+,9.1,0,0,1,0,"Documentary,Family,History,War",Bosnia and Herzegovina,"Bosnian,English",56.0
3560,3561,The Dark Knight,2008,13+,9.0,0,1,0,0,"Action,Crime,Drama,Thriller",United Kingdom,"English,Mandarin",152.0
6840,6841,Peter Gabriel: Secret World Live,1993,all,8.9,0,0,1,0,"Documentary,Music",Canada,English,102.0
4829,4830,The Mountain II,2016,all,8.9,0,0,1,0,"Action,Drama,War",Turkey,Turkish,135.0
7643,7644,Machine Gun Preacher Documentary,2014,16+,8.8,0,0,1,0,Documentary,Australia,English,73.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15735,15736,The Legend of the Titanic,1999,all,1.6,0,0,1,0,"Animation,Family,Fantasy,Romance",Italy,Italian,84.0
15837,15838,Life's a Jungle: Africa's Most Wanted,2012,all,1.6,0,0,1,0,"Animation,Family",United States,English,101.0
16631,16632,Jonas Brothers: The Concert Experience,2009,all,1.6,0,0,0,1,"Documentary,Music",United States,English,76.0
15556,15557,Diamond Dawgs,2009,18+,1.5,0,0,1,0,"Action,Crime,Drama",United States,English,90.0
13681,13682,Justin Bieber: Rise to Fame,2011,all,1.0,0,0,1,0,Documentary,United Kingdom,English,65.0

## Country drop duplicates creating one Service column

In [178]:
#Full Data Frame with unified Service column
print("----------------------------")
print(f"Complete Country adding Service column")
print("----------------------------")
dropcountry_df

----------------------------
Complete Country adding Service column
----------------------------

,ID,Title,Year,Age,IMDb,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime,Total Services
7491,7492,Finding Family,2013,13+,9.1,0,0,1,0,"Documentary,Family,History,War",Bosnia and Herzegovina,"Bosnian,English",56.0,1
3560,3561,The Dark Knight,2008,13+,9.0,0,1,0,0,"Action,Crime,Drama,Thriller",United Kingdom,"English,Mandarin",152.0,1
6840,6841,Peter Gabriel: Secret World Live,1993,all,8.9,0,0,1,0,"Documentary,Music",Canada,English,102.0,1
4829,4830,The Mountain II,2016,all,8.9,0,0,1,0,"Action,Drama,War",Turkey,Turkish,135.0,1
7643,7644,Machine Gun Preacher Documentary,2014,16+,8.8,0,0,1,0,Documentary,Australia,English,73.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15735,15736,The Legend of the Titanic,1999,all,1.6,0,0,1,0,"Animation,Family,Fantasy,Romance",Italy,Italian,84.0,1
15837,15838,Life's a Jungle: Africa's Most Wanted,2012,all,1.6,0,0,1,0,"Animation,Family",United States,English,101.0,1
16631,16632,Jonas Brothers: The Concert Experience,2009,all,1.6,0,0,0,1,"Documentary,Music",United States,English,76.0,1
15556,15557,Diamond Dawgs,2009,18+,1.5,0,0,1,0,"Action,Crime,Drama",United States,English,90.0,1
13681,13682,Justin Bieber: Rise to Fame,2011,all,1.0,0,0,1,0,Documentary,United Kingdom,English,65.0,1

## Now let's work with every movie instead of only the unique ones...¶

In [179]:
dropcountry_df.columns

Index(['ID', 'Title', 'Year', 'Age', 'IMDb', 'Netflix', 'Hulu', 'Prime Video',
       'Disney+', 'Genres', 'Country', 'Language', 'Runtime',
       'Total Services'],
      dtype='object')

In [181]:
dropcountry_df["Total Services"] = dropcountry_df["Netflix"]+dropcountry_df["Hulu"]+dropcountry_df["Prime Video"]+dropcountry_df["Disney+"]

uniquecountry_movies_df = dropcountry_df[dropcountry_df["Total Services"]<2]
uniquecountry_movies_df

C:\Users\gloam\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,ID,Title,Year,Age,IMDb,Netflix,Hulu,Prime Video,Disney+,Genres,Country,Language,Runtime,Total Services
7491,7492,Finding Family,2013,13+,9.1,0,0,1,0,"Documentary,Family,History,War",Bosnia and Herzegovina,"Bosnian,English",56.0,1
3560,3561,The Dark Knight,2008,13+,9.0,0,1,0,0,"Action,Crime,Drama,Thriller",United Kingdom,"English,Mandarin",152.0,1
6840,6841,Peter Gabriel: Secret World Live,1993,all,8.9,0,0,1,0,"Documentary,Music",Canada,English,102.0,1
4829,4830,The Mountain II,2016,all,8.9,0,0,1,0,"Action,Drama,War",Turkey,Turkish,135.0,1
7643,7644,Machine Gun Preacher Documentary,2014,16+,8.8,0,0,1,0,Documentary,Australia,English,73.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15735,15736,The Legend of the Titanic,1999,all,1.6,0,0,1,0,"Animation,Family,Fantasy,Romance",Italy,Italian,84.0,1
15837,15838,Life's a Jungle: Africa's Most Wanted,2012,all,1.6,0,0,1,0,"Animation,Family",United States,English,101.0,1
16631,16632,Jonas Brothers: The Concert Experience,2009,all,1.6,0,0,0,1,"Documentary,Music",United States,English,76.0,1
15556,15557,Diamond Dawgs,2009,18+,1.5,0,0,1,0,"Action,Crime,Drama",United States,English,90.0,1
13681,13682,Justin Bieber: Rise to Fame,2011,all,1.0,0,0,1,0,Documentary,United Kingdom,English,65.0,1

In [182]:
uniquecountry_movies_df.columns

Index(['ID', 'Title', 'Year', 'Age', 'IMDb', 'Netflix', 'Hulu', 'Prime Video',
       'Disney+', 'Genres', 'Country', 'Language', 'Runtime',
       'Total Services'],
      dtype='object')

In [183]:
uniquecountry_movies_df = pd.melt(uniquecountry_movies_df, id_vars = ['ID', 'Title', 'Year', 'Age', 'IMDb', 'Genres', 'Country',
                                                                      'Language', 'Runtime', "Total Services"], 
                      value_vars= ['Netflix', 'Hulu', 'Prime Video','Disney+'], var_name = "Service")

#uniquecountry_movies_df

In [184]:

uniquecountry_movies_df = uniquecountry_movies_df[uniquecountry_movies_df["value"]==1]

uniquecountry_movies_df.drop(columns=["value"], inplace=True)

uniquecountry_movies_df

,ID,Title,Year,Age,IMDb,Genres,Country,Language,Runtime,Total Services,Service
6,1,Inception,2010,13+,8.8,"Action,Adventure,Sci-Fi,Thriller",United Kingdom,"English,Japanese,French",148.0,1,Netflix
10,2,The Matrix,1999,18+,8.7,"Action,Sci-Fi",United States,English,136.0,1,Netflix
15,1539,Luciano Mellera: Infantiloide,2018,13+,8.6,Comedy,Argentina,Spanish,66.0,1,Netflix
16,2196,Hikaru Utada Laughter in the Dark Tour 2018,2019,all,8.6,Music,Japan,Japanese,141.0,1,Netflix
26,48,Senna,2010,13+,8.5,"Documentary,Biography,Sport",France,"English,Portuguese,French,Japanese",106.0,1,Netflix
...,...,...,...,...,...,...,...,...,...,...,...
26887,16638,Inspector Gadget 2,2003,all,3.4,"Action,Comedy,Crime,Family,Sci-Fi",United States,English,89.0,1,Disney+
26889,16672,George of the Jungle 2,2003,7+,3.3,"Adventure,Comedy,Family",Australia,English,87.0,1,Disney+
27030,16688,Kazaam,1996,7+,3.0,"Comedy,Family,Fantasy,Musical",United States,English,93.0,1,Disney+
27180,16526,Hannah Montana & Miley Cyrus: Best of Both Wor...,2008,all,2.4,"Documentary,Music",United States,English,74.0,1,Disney+
27241,16632,Jonas Brothers: The Concert Experience,2009,all,1.6,"Documentary,Music",United States,English,76.0,1,Disney+

In [185]:
uniquecountry_movies_df.loc[uniquecountry_movies_df['Year'].idxmax()]

ID                                               284
Title             Crip Camp: A Disability Revolution
Year                                            2020
Age                                              18+
IMDb                                             7.8
Genres                                   Documentary
Country                                United States
Language                                     English
Runtime                                          106
Total Services                                     1
Service                                      Netflix
Name: 325, dtype: object

In [186]:
uniquecountry_movies_df.loc[uniquecountry_movies_df['Year'].idxmin()]

ID                                                        4468
Title                                       A Trip to the Moon
Year                                                      1902
Age                                                        all
IMDb                                                       8.2
Genres            Short,Action,Adventure,Comedy,Fantasy,Sci-Fi
Country                                                 France
Language                                           None,French
Runtime                                                     13
Total Services                                               1
Service                                            Prime Video
Name: 13708, dtype: object

In [187]:
uniquecountry_movies_df[uniquecountry_movies_df['Year']==uniquecountry_movies_df['Year'].max()]

,ID,Title,Year,Age,IMDb,Genres,Country,Language,Runtime,Total Services,Service
325,284,Crip Camp: A Disability Revolution,2020,18+,7.8,Documentary,United States,English,106.0,1,Netflix
721,159,Miss Americana,2020,18+,7.4,Documentary,United States,English,85.0,1,Netflix
738,1581,Dave Chappelle: The Kennedy Center Mark Twain ...,2020,18+,7.4,Comedy,United States,English,90.0,1,Netflix
859,2538,Go! Go! Cory Carson: The Chrissy,2020,all,7.3,"Animation,Short,Family",United States,English,42.0,1,Netflix
1031,66,To All the Boys I've Loved Before,2020,13+,7.2,"Comedy,Drama,Romance",United States,English,99.0,1,Netflix
1396,465,The Half of It,2020,13+,7.0,"Comedy,Romance",United States,"Spanish,Hindi,English,Mandarin,French",104.0,1,Netflix
1740,113,Extraction,2020,18+,6.8,"Action,Thriller",United States,"English,Hindi,Bengali",116.0,1,Netflix
2116,1190,Becoming,2020,7+,6.6,Documentary,United States,English,89.0,1,Netflix
2118,1614,Lady Driver,2020,7+,6.6,Sport,United States,English,104.0,1,Netflix
2316,484,All the Bright Places,2020,18+,6.5,"Drama,Romance",United States,English,107.0,1,Netflix
2433,249,The Willoughbys,2020,7+,6.4,"Animation,Adventure,Comedy,Family",Canada,English,90.0,1,Netflix
2467,1151,Isi & Ossi,2020,18+,6.4,"Comedy,Romance",Germany,German,113.0,1,Netflix
2520,466,Tigertail,2020,7+,6.4,Drama,United States,"English,Min Nan,Mandarin",91.0,1,Netflix
2711,775,The Occupant,2020,18+,6.3,"Drama,Thriller",Spain,Spanish,103.0,1,Netflix
2965,454,Spenser Confidential,2020,18+,6.2,"Action,Comedy,Crime,Drama,Thriller",United States,English,111.0,1,Netflix
3190,436,Uncorked,2020,13+,6.1,Drama,United States,English,104.0,1,Netflix
3195,698,Sergio,2020,18+,6.1,"Biography,Drama,History,Romance",United States,"English,Portuguese,Spanish,French",118.0,1,Netflix
3200,939,Lost Girls,2020,18+,6.1,"Drama,Mystery,Thriller",United States,English,95.0,1,Netflix
3395,556,To All the Boys: P.S. I Still Love You,2020,16+,6.0,"Comedy,Romance",United States,English,101.0,1,Netflix
3557,692,Horse Girl,2020,18+,5.9,"Drama,Mystery,Thriller",United States,English,103.0,1,Netflix
3559,754,All Day and a Night,2020,18+,5.9,Drama,United States,English,121.0,1,Netflix
3567,1166,Pete Davidson: Alive from New York,2020,18+,5.9,Comedy,United States,English,49.0,1,Netflix
3771,1172,A Fall From Grace,2020,18+,5.8,"Drama,Thriller",United States,English,115.0,1,Netflix
4275,1377,Love Wedding Repeat,2020,18+,5.5,Comedy,Italy,English,100.0,1,Netflix
4311,1814,Roped,2020,7+,5.5,"Drama,Romance",United States,English,91.0,1,Netflix
4743,2264,#cats_the_mewvie,2020,16+,5.2,Documentary,Canada,English,90.0,1,Netflix
4798,1074,Dangerous Lies,2020,16+,5.2,"Drama,Mystery,Thriller",United States,English,96.0,1,Netflix
4952,1607,Dragonheart: Vengeance,2020,13+,5.1,"Action,Adventure,Drama,Fantasy,Sci-Fi",United States,English,97.0,1,Netflix
5041,1405,Earth and Blood,2020,18+,5.0,"Action,Crime,Thriller",Belgium,French,80.0,1,Netflix
5928,2172,Fronteras,2020,18+,4.2,"Drama,Romance",Spain,"Spanish,Arabic",96.0,1,Netflix
5938,2370,The Last Thing He Wanted,2020,18+,4.2,"Crime,Drama,Mystery,Thriller",United States,"English,Spanish,French",115.0,1,Netflix
6379,3418,John Henry,2020,18+,3.5,"Drama,Thriller",United States,English,91.0,1,Netflix
8220,3691,Big Time Adolescence,2020,18+,7.0,Comedy,United States,English,91.0,1,Hulu
12579,4266,My Valentine,2020,13+,4.4,"Comedy,Romance",Thailand,Thai,90.0,1,Hulu
18294,5338,M.O.M. Mothers of Monsters,2020,18+,5.3,Thriller,United States,English,98.0,1,Prime Video
19950,9143,The Great War,2020,18+,3.6,"Drama,War",United States,English,108.0,1,Prime Video
20600,16549,The Disney Family Singalong,2020,all,8.1,"Family,Musical",United States,English,NaN,1,Disney+
21079,16250,Onward,2020,7+,7.5,"Animation,Adventure,Comedy,Family,Fantasy",United States,English,102.0,1,Disney+
23507,16466,Stargirl,2020,7+,6.2,"Action,Adventure,Crime,Drama,Fantasy,Sci-Fi",United States,English,45.0,1,Disney+
23730,16404,Timmy Failure: Mistakes Were Made,2020,7+,6.1,"Adventure,Comedy,Drama,Family,Fantasy",United States,English,99.0,1,Disney+

In [188]:
uniquecountry_movies_df[uniquecountry_movies_df['Year']==uniquecountry_movies_df['Year'].min()]

,ID,Title,Year,Age,IMDb,Genres,Country,Language,Runtime,Total Services,Service
13708,4468,A Trip to the Moon,1902,all,8.2,"Short,Action,Adventure,Comedy,Fantasy,Sci-Fi",France,"None,French",13.0,1,Prime Video